{
  "swagger": "2.0",
  "info": {
    "description": "Documentation for Free Mentors service",
    "version": "1.0.0",
    "title": "Free Mentor",
    "termsOfService": "https://kimenyikevin.github.io/FreeMentor/UI/",
    "contact": {
      "email": "kimenyikevin@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:3000",
  "basePath": "/api/v2/auth",
  "tags": [
    {
      "name": "signup",
      "description": "New user registration"
    },
    {
      "name": "signin",
      "description": "Existing user signin"
    },
    {
      "name": "Change user to Mentor",
      "description": "Admin can change user to mentor"
    },
    {
      "name": "view all Mentors",
      "description": "view all mentors"
    },
    {
      "name": "Specific mentor",
      "description": "view specific mentor details"
    },
    {
      "name": "Create Mentorship session",
      "description": "user can create mentorship session"
    },
    {
      "name": "Reject Mentorship session",
      "description": "mentor can reject mentorship session request"
    },
    {
      "name": "Accept Mentorship session",
      "description": "mentor can accept mentorship session request"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/signup": {
      "post": {
        "tags": [
          "signup"
        ],
        "summary": "Create New Account",
        "description": "If you don't have account yet register",
        "operationId": "createUser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Created user object",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User created successfully",
            "schema": {
              "type": "object",
              "example":{
                  "status": 201,
                  "message": "User created successfully",
                  "data": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNTY3Mjg2NTIxfQ.fJyiqLzJPs8D3NiUz_a0-NQBN1YUEfAP3sIyjhNkaqk",
                      "id": 5,
                      "firstName": "kevin",
                      "lastName": "kevin",
                      "email": "kimenyis@gmail.com",
                      "address": "kigali",
                      "bio": " engineeer",
                      "status": "user",
                      "occupation": "engineer",
                      "expertise": " engineer"
                  }
              }
            }
          },
          "401": {
            "description": "user already exist"
          }
        }
      }
    },
    "/signin": {
      "post": {
        "tags": [
          "signin"
        ],
        "summary": "user sign in",
        "description": "",
        "operationId": "loginUser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "login user object",
            "required": true,
            "schema": {
              "$ref": "#/definitions/login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "user successful login",
            "schema": {
              "type": "string",
              "example":{
                "status": 200,
                "message": "User is successfully logged in",
                "data": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlclR5cGUiOiJ1c2VyIiwiZW1haWwiOiJoYWJpbWFuYWVtbXlAZ21haWwuY29tIiwiaWF0IjoxNTY3Mjg2NjczfQ.PNeEYEUwEVI0DNtzyyBDh9DfMD5t0tABtex0gVfGmtg",
                    "id": 2,
                    "firstName": "habimana",
                    "lastName": "emmy",
                    "email": "habimanaemmy@gmail.com",
                    "address": "kigali",
                    "bio": "engineer",
                    "status": "user",
                    "occupation": "engineer",
                    "expertise": "engineer"
                }
              }
            }
          },
          "400": {
            "description": "Invalid username/password supplied"
          },
          "404":{
            "description": "E-mail does not exist"
          },
          "401": {
            "description": " E-mail or password is wrong"
          }
        }
      }
    },
    "/user/{id}": {
        "patch": {
          "tags": [
            "Change user to Mentor"
          ],
          "summary": "change user to mentor",
          "description": "",
          "operationId": "getuserById",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "ID of the user",
              "required": true,
              "type": "integer",
              "format": "int64"
            },
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             }
          ],
          "responses": {
            "200": {
              "description": "User account changed to mentor",
              "schema":{
                "type": "object",
                "example":{
                  "status": 200,
                  "data": {
                      "message": "User account changed to mentor",
                      "id": 2,
                      "firstName": "habimana",
                      "lastName": "emmy",
                      "email": "habimanaemmy@gmail.com",
                      "address": "kigali",
                      "bio": "engineer",
                      "status": "mentor",
                      "occupation": "engineer",
                      "expertise": "engineer"
                  }
                }
              }
            },
            "401": {
              "description": "you are not an admin"
            },
            "404": {
              "description": "you do not have access to this service"
            }
          }
        }
      },
      "/mentors": {
        "get": {
          "tags": [
            "view all Mentors"
          ],
          "summary": "Returns all mentors",
          "description": "",
          "operationId": "get all mentors",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             }
          ],
          "responses": {
            "200": {
              "description": "List of all mentor",
              "schema": {
                "type": "object",
                "example": {
                  "id": 4,
                  "firstName": "bavakure",
                  "lastName": "eric",
                  "email": "kimenyike@gmail.com",
                  "password": "kigali",
                  "address": "kigali",
                  "bio": "engineer",
                  "status": "mentor",
                  "occupation": "engineer",
                  "expertise": "engineer"
                }
              }
            },
            "401":{
              "description": "you are not user"
            }
          }
        }
      },
      "/mentors{id}": {
        "get": {
          "tags": [
            "Specific mentor"
          ],
          "summary": "Returns one mentor",
          "description": " ",
          "operationId": "getmentor",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "ID of the mentor",
              "required": true,
              "type": "integer",
              "format": "int64"
            },
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             }
          ],
          "responses": {
            "200": {
              "description": "specific mentor",
              "schema": {
                "type": "object",
                "example": {
                  "id": 4,
                  "firstName": "bavakure",
                  "lastName": "eric",
                  "email": "kimenyike@gmail.com",
                  "password": "kigali",
                  "address": "kigali",
                  "bio": "engineer",
                  "status": "mentor",
                  "occupation": "engineer",
                  "expertise": "engineer"
                }
              }
            }
          }
        }
      },
      "/sessions": {
        "post": {
          "tags": [
            "Create Mentorship session"
          ],
          "summary": "Create mentorship session",
          "description": "",
          "operationId": "create sessions",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             },
            {
              "in": "body",
              "name": "body",
              "description": "Created session object",
              "required": true,
              "schema": {
                "$ref": "#/definitions/sessions"
              }
            }
          ],
          "responses": {
            "201": {
              "description": "sessions created successfully",
              "schema":{
                "type":"object",
                "example": {
                  "status": 200,
                  "data": {
                      "Sessionid": 5,
                      "mentorId": 1,
                      "menteeId": 5,
                      "questions": "i need help",
                      "status": "pending"
                  }
                }
              }
            }
          }
        }
      },
      "/sessions/{id}/accept": {
        "patch": {
          "tags": [
            "Accept Mentorship session"
          ],
          "summary": "reject mentorship request",
          "description": "",
          "operationId": "acceptRequest",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             },
            {
              "in": "path",
              "name": "id",
              "description": "acccept mentorship request",
              "required": true
            }
          ],
          "responses": {
            "201": {
              "description": "accepted mentorship successfully",
              "schema":{
                "example":{
                  "status": 200,
                  "data": {
                      "Sessionid": 2,
                      "mentorId": 3,
                      "menteeId": 1,
                      "questions": "i need help",
                      "menteeEmail": "kimenyikevin@gmail.com",
                      "status": "accepted"
                  }
                }
              }
            },
            "404":{
              "description": "data not found"
            }
          }
        }
      },
      "/sessions/{id}/reject": {
        "patch": {
          "tags": [
            "Reject Mentorship session"
          ],
          "summary": "reject mentorship request",
          "description": "",
          "operationId": "rejectRequest",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "authorization",
              "in": "header",
              "required": true,
              "type": "string",
              "description": "The token to provide in this box must start with adminToken then space"
             },
            {
              "in": "path",
              "name": "id",
              "description": "acccept mentorship request",
              "required": true
            }
          ],
          "responses": {
            "201": {
              "description": "rejected mentorship successfully",
              "schema":{
                "example":{
                  "status": 200,
                  "data": {
                      "Sessionid": 2,
                      "mentorId": 3,
                      "menteeId": 1,
                      "questions": "i need help",
                      "menteeEmail": "kimenyikevin@gmail.com",
                      "status": "reject"
                  }
                }
              }
            },
            "404":{
              "description": "data not found"
            }
          }
        }
      }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "bio": {
          "type": "string"
        },
        "occupation": {
          "type": "string"
        },
        "expertise": {
          "type": "string"
        }
      }
    },
    "login": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "sessions": {
      "type": "object",
      "properties": {
        "mentorId": {
          "type": "integer"
        },
        "questions": {
          "type": "string"
        }
      }
    }
  },
  "externalDocs": {
    "description": "FreeMentor",
    "url": "https://kimenyikevin.github.io/FreeMentor/UI "
  }
}